 
version: "2"
volumes:
  db:
  api:
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=root_password_here
      - MARIADB_PASSWORD=7654321
      - MARIADB_USER=user
      - MARIADB_DATABASE=db
      - TZ=America/Bogota
    ports:
      - '8940:3306'
    volumes:
      - 'db:/var/lib/mysql/'
  api: 
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: 7654321
      DB_DATABASE: db
    volumes: 
      - 'api:/var/www/html'
    depends_on:
      - mariadb
    
  nginx:
      build:
          context: .
          dockerfile: nginx.dockerfile
      depends_on:
          - php
          - mysql
      container_name: nginx
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./src:/var/www/html
      networks:
          - laravel

  php:
      build:
          context: .
          dockerfile: php.dockerfile
      container_name: php
      volumes:
          - ./src:/var/www/html
      networks:
          - laravel
  
  composer:
      image: composer:latest
      container_name: composer
      volumes:
          - ./src:/var/www/html
      working_dir: /var/www/html
      networks:
          - laravel

  artisan:
      build:
          context: .
          dockerfile: php.dockerfile
      container_name: artisan
      volumes:
          - ./src:/var/www/html
      working_dir: /var/www/html
      entrypoint: ['php', 'artisan']
      networks:
          - laravel

  npm:
      image: node:current-alpine
      container_name: npm
      volumes:
          - ./src:/var/www/html
      working_dir: /var/www/html
      entrypoint: ['npm']
      networks:
          - laravel

