# Utiliza una imagen base con Apache y PHP
FROM phpmyadmin/phpmyadmin:latest

# Copia el archivo de configuración personalizado de Apache
COPY apache2.conf /etc/apache2/apache2.conf

# Reinicia el servicio de Apache al iniciar el contenedor
CMD ["apache2-foreground"]
# Construir la imagen
#docker build -t mi_phpmyadmin .

# Ejecutar el contenedor
#docker run -d --name mi_phpmyadmin --network mi_red -p 8081:80 mi_phpmyadmin

